import { useEffect, useState } from "react";
import { Button, Card, Form, Input, InputNumber, Modal, Popconfirm, Rate, Select, Space, Spin, Tag, message } from "antd";
import { Edit, MapPin, Plus, Star, Trash2, Trophy } from "lucide-react";
import { api, formatCurrency, type Court, type Field } from "../../lib/api";

type FieldFormValues = Partial<Pick<Field, "name" | "address" | "priceFrom" | "rating" | "image" | "status">>;
type CourtFormValues = Partial<Pick<Court, "name" | "type" | "price" | "status" | "capacity" | "description" | "imageUrl">>;

const apiErrorMessage = (error: unknown, fallback: string) =>
  (error as { response?: { data?: { message?: string } } }).response?.data?.message || fallback;

export default function Facilities() {
  const [fields, setFields] = useState<Field[]>([]); const [courts, setCourts] = useState<Court[]>([]); const [loading, setLoading] = useState(true);
  const [fieldOpen, setFieldOpen] = useState(false); const [courtOpen, setCourtOpen] = useState(false); const [selected, setSelected] = useState<Field | null>(null); const [editingField, setEditingField] = useState<Field | null>(null); const [editingCourt, setEditingCourt] = useState<Court | null>(null);
  const [fieldForm] = Form.useForm(); const [courtForm] = Form.useForm();
  const load = async () => { try { const [f, c] = await Promise.all([api.get<Field[]>("/fields"), api.get<Court[]>("/courts")]); setFields(f.data); setCourts(c.data); } catch { message.error("Không thể tải dữ liệu cơ sở"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const openField = (field?: Field) => { setEditingField(field || null); fieldForm.setFieldsValue(field || { priceFrom: 0, rating: 0, status: "active" }); setFieldOpen(true); };
  const saveField = async (values: FieldFormValues) => { try { if (editingField) await api.put(`/fields/${editingField.id}`, values); else await api.post("/fields", values); message.success("Đã lưu cơ sở"); setFieldOpen(false); load(); } catch (error: unknown) { message.error(apiErrorMessage(error, "Không thể lưu cơ sở")); } };
  const deleteField = async (id: number) => { try { await api.delete(`/fields/${id}`); message.success("Đã xóa cơ sở"); load(); } catch (error: unknown) { message.error(apiErrorMessage(error, "Không thể xóa cơ sở")); } };
  const openCourts = (field: Field) => { setSelected(field); };
  const openCourt = (court?: Court) => { setEditingCourt(court || null); courtForm.setFieldsValue(court || { fieldId: selected?.id, type: "Bóng rổ 5x5", status: "active", capacity: 10, price: 0 }); setCourtOpen(true); };
  const saveCourt = async (values: CourtFormValues) => { try { if (editingCourt) await api.put(`/courts/${editingCourt.id}`, values); else await api.post("/courts", { ...values, fieldId: selected?.id }); message.success("Đã lưu sân con"); setCourtOpen(false); load(); } catch (error: unknown) { message.error(apiErrorMessage(error, "Không thể lưu sân con")); } };
  const deleteCourt = async (id: number) => { try { await api.delete(`/courts/${id}`); message.success("Đã xóa sân con"); load(); } catch (error: unknown) { message.error(apiErrorMessage(error, "Không thể xóa sân con")); } };
  if (loading) return <div className="flex justify-center py-40"><Spin size="large" /></div>;
  const selectedCourts = courts.filter((court) => court.fieldId === selected?.id);
  return <div className="animate-in fade-in duration-500 pb-10">
    <div className="mb-8 flex flex-wrap justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-black uppercase tracking-widest text-yellow-400"><Trophy size={14} /> Venue operations</div><h1 className="text-3xl font-black text-white">Quản lý cơ sở sân bóng rổ</h1><p className="mt-2 font-medium text-gray-500">Quản lý cụm sân, giá, hình ảnh và sân con của từng cơ sở.</p></div><Button type="primary" size="large" onClick={() => openField()} className="!h-12 !border-0 !bg-yellow-500 !px-6 !font-bold !text-black"><Plus size={18} /> Thêm cơ sở</Button></div>
    <div className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3">{fields.map((field) => <Card key={field.id} className="field-card overflow-hidden !border-white/10 !bg-zinc-900" cover={field.image ? <img src={field.image} alt={`Ảnh ${field.name}`} className="h-44 w-full object-cover" /> : <div className="flex h-44 items-center justify-center bg-gradient-to-br from-yellow-500/20 to-zinc-900"><Trophy className="text-yellow-400" size={42} /></div>}><div className="space-y-3"><div className="flex justify-between gap-2"><h2 className="m-0 text-lg font-black text-white">{field.name}</h2><Tag color={field.status === "active" ? "success" : "default"}>{field.status === "active" ? "Hoạt động" : "Tạm dừng"}</Tag></div><div className="flex gap-2 text-sm text-gray-400"><MapPin size={16} />{field.address || "Chưa có địa chỉ"}</div><div className="flex items-center justify-between"><span className="font-bold text-yellow-400">Từ {formatCurrency(field.priceFrom)}</span><span className="flex items-center gap-1 text-gray-300"><Star size={15} className="fill-yellow-400 text-yellow-400" />{Number(field.rating || 0).toFixed(1)}</span></div><div className="flex gap-2"><Button className="flex-1" onClick={() => openCourts(field)}>Danh sách sân ({courts.filter((court) => court.fieldId === field.id).length})</Button><Button aria-label={`Sửa ${field.name}`} type="text" onClick={() => openField(field)}><Edit size={18} /></Button><Popconfirm title="Xóa cơ sở này?" onConfirm={() => deleteField(field.id)} okText="Xóa" cancelText="Hủy"><Button aria-label={`Xóa ${field.name}`} type="text" danger><Trash2 size={18} /></Button></Popconfirm></div></div></Card>)}</div>
    <Modal title={editingField ? "Cập nhật cơ sở" : "Thêm cơ sở"} open={fieldOpen} onCancel={() => setFieldOpen(false)} footer={null}><Form form={fieldForm} layout="vertical" onFinish={saveField}><Form.Item name="name" label="Tên cơ sở" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="address" label="Địa chỉ" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="priceFrom" label="Giá từ (VNĐ/giờ)" rules={[{ required: true }]}><InputNumber min={0} className="w-full" /></Form.Item><Form.Item name="rating" label="Đánh giá"><Rate allowHalf /></Form.Item><Form.Item name="image" label="Ảnh đại diện (URL)"><Input /></Form.Item><Form.Item name="status" label="Trạng thái"><Select options={[{ value: "active", label: "Hoạt động" }, { value: "inactive", label: "Tạm dừng" }]} /></Form.Item><Button type="primary" htmlType="submit" block>Lưu cơ sở</Button></Form></Modal>
    <Modal title={`Danh sách sân — ${selected?.name || ""}`} open={Boolean(selected)} onCancel={() => setSelected(null)} footer={null} width={720}><div className="mb-4 flex justify-end"><Button type="primary" onClick={() => openCourt()}><Plus size={16} /> Thêm sân con</Button></div><div className="space-y-3">{selectedCourts.map((court) => <div key={court.id} className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><div><div className="font-bold">{court.name}</div><div className="text-sm text-slate-500">{court.type} · {formatCurrency(court.price)}/giờ</div></div><Space><Tag color={court.status === "active" ? "success" : "warning"}>{court.status}</Tag><Button type="text" onClick={() => openCourt(court)}><Edit size={17} /></Button><Popconfirm title="Xóa sân con này?" onConfirm={() => deleteCourt(court.id)}><Button type="text" danger><Trash2 size={17} /></Button></Popconfirm></Space></div>)}</div></Modal>
    <Modal title={editingCourt ? "Cập nhật sân con" : "Thêm sân con"} open={courtOpen} onCancel={() => setCourtOpen(false)} footer={null}><Form form={courtForm} layout="vertical" onFinish={saveCourt}><Form.Item name="name" label="Tên sân con" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="type" label="Loại sân"><Select options={[{ value: "Bóng rổ 5x5", label: "Bóng rổ 5x5" }, { value: "Bóng rổ 3x3", label: "Bóng rổ 3x3" }]} /></Form.Item><Form.Item name="price" label="Giá thuê/giờ" rules={[{ required: true }]}><InputNumber min={0} className="w-full" /></Form.Item><Form.Item name="status" label="Trạng thái"><Select options={[{ value: "active", label: "Hoạt động" }, { value: "maintenance", label: "Bảo trì" }, { value: "inactive", label: "Tạm dừng" }]} /></Form.Item><Form.Item name="capacity" label="Sức chứa"><InputNumber min={1} className="w-full" /></Form.Item><Form.Item name="description" label="Mô tả"><Input.TextArea rows={3} /></Form.Item><Form.Item name="imageUrl" label="Ảnh sân con (URL)"><Input /></Form.Item><Button type="primary" htmlType="submit" block>Lưu sân con</Button></Form></Modal>
  </div>;
}
